### ISSUE TITLE
Allow for deleting of latest message, if submitter = user.

### ISSUE THREAD

**Issue by xuatz** [daryltanwk/ChatOrDie2#6]

**Comment by daryltanwk** [comment]
ok this sounds reasonable. HAHA!

**Comment by daryltanwk** [comment]
There is actually already logic in place to remove last message if you are the submitter OR the starter of the story.

#### Undocumented Code

> Meteor.call('deleteStorySegment','<storyId>')

<storyId> is found in the address bar as follows:

> route: /3word/ypaoBFdXg8LTKfKfg
> 
> storyId: ypaoBFdXg8LTKfKfg

I will implement the UI for the code later.
